/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PageIdRouteImport } from './routes/$pageId'
import { Route as TemplatesRouteRouteImport } from './routes/templates/route'
import { Route as SiteRouteRouteImport } from './routes/site/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SitePageIdRouteImport } from './routes/site/$pageId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PageIdRoute = PageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRouteRoute = TemplatesRouteRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const SitePageIdRoute = SitePageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => SiteRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/site': typeof SiteRouteRouteWithChildren
  '/templates': typeof TemplatesRouteRouteWithChildren
  '/$pageId': typeof PageIdRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/site/$pageId': typeof SitePageIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/site': typeof SiteRouteRouteWithChildren
  '/$pageId': typeof PageIdRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/site/$pageId': typeof SitePageIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/site': typeof SiteRouteRouteWithChildren
  '/templates': typeof TemplatesRouteRouteWithChildren
  '/$pageId': typeof PageIdRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/site/$pageId': typeof SitePageIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/site'
    | '/templates'
    | '/$pageId'
    | '/about'
    | '/login'
    | '/site/$pageId'
    | '/dashboard/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/site'
    | '/$pageId'
    | '/about'
    | '/login'
    | '/site/$pageId'
    | '/dashboard'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/site'
    | '/templates'
    | '/$pageId'
    | '/about'
    | '/login'
    | '/site/$pageId'
    | '/dashboard/'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  TemplatesRouteRoute: typeof TemplatesRouteRouteWithChildren
  PageIdRoute: typeof PageIdRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pageId': {
      id: '/$pageId'
      path: '/$pageId'
      fullPath: '/$pageId'
      preLoaderRoute: typeof PageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/site/$pageId': {
      id: '/site/$pageId'
      path: '/$pageId'
      fullPath: '/site/$pageId'
      preLoaderRoute: typeof SitePageIdRouteImport
      parentRoute: typeof SiteRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface SiteRouteRouteChildren {
  SitePageIdRoute: typeof SitePageIdRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SitePageIdRoute: SitePageIdRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

interface TemplatesRouteRouteChildren {
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const TemplatesRouteRouteChildren: TemplatesRouteRouteChildren = {
  TemplatesIndexRoute: TemplatesIndexRoute,
}

const TemplatesRouteRouteWithChildren = TemplatesRouteRoute._addFileChildren(
  TemplatesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SiteRouteRoute: SiteRouteRouteWithChildren,
  TemplatesRouteRoute: TemplatesRouteRouteWithChildren,
  PageIdRoute: PageIdRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
