/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteRouteImport } from './routes/_marketing/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingLoginRouteImport } from './routes/_marketing/login'
import { Route as Live_sitePageIdRouteImport } from './routes/_live_site/$pageId'
import { Route as AppDashboardRouteRouteImport } from './routes/_app/dashboard/route'
import { Route as AppSitePageIdRouteImport } from './routes/_app/site/$pageId'

const MarketingRouteRoute = MarketingRouteRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingLoginRoute = MarketingLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const Live_sitePageIdRoute = Live_sitePageIdRouteImport.update({
  id: '/_live_site/$pageId',
  path: '/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRouteRoute = AppDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSitePageIdRoute = AppSitePageIdRouteImport.update({
  id: '/site/$pageId',
  path: '/site/$pageId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/dashboard': typeof AppDashboardRouteRoute
  '/$pageId': typeof Live_sitePageIdRoute
  '/login': typeof MarketingLoginRoute
  '/site/$pageId': typeof AppSitePageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/dashboard': typeof AppDashboardRouteRoute
  '/$pageId': typeof Live_sitePageIdRoute
  '/login': typeof MarketingLoginRoute
  '/site/$pageId': typeof AppSitePageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_marketing': typeof MarketingRouteRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRouteRoute
  '/_live_site/$pageId': typeof Live_sitePageIdRoute
  '/_marketing/login': typeof MarketingLoginRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_app/site/$pageId': typeof AppSitePageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/$pageId' | '/login' | '/site/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/$pageId' | '/login' | '/site/$pageId'
  id:
    | '__root__'
    | '/_app'
    | '/_marketing'
    | '/_app/dashboard'
    | '/_live_site/$pageId'
    | '/_marketing/login'
    | '/_marketing/'
    | '/_app/site/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  MarketingRouteRoute: typeof MarketingRouteRouteWithChildren
  Live_sitePageIdRoute: typeof Live_sitePageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/login': {
      id: '/_marketing/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MarketingLoginRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_live_site/$pageId': {
      id: '/_live_site/$pageId'
      path: '/$pageId'
      fullPath: '/$pageId'
      preLoaderRoute: typeof Live_sitePageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/site/$pageId': {
      id: '/_app/site/$pageId'
      path: '/site/$pageId'
      fullPath: '/site/$pageId'
      preLoaderRoute: typeof AppSitePageIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardRouteRoute: typeof AppDashboardRouteRoute
  AppSitePageIdRoute: typeof AppSitePageIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRouteRoute: AppDashboardRouteRoute,
  AppSitePageIdRoute: AppSitePageIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface MarketingRouteRouteChildren {
  MarketingLoginRoute: typeof MarketingLoginRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteRouteChildren: MarketingRouteRouteChildren = {
  MarketingLoginRoute: MarketingLoginRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteRouteWithChildren = MarketingRouteRoute._addFileChildren(
  MarketingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  MarketingRouteRoute: MarketingRouteRouteWithChildren,
  Live_sitePageIdRoute: Live_sitePageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
