/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteRouteImport } from './routes/_marketing/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as MarketingChar123PageIdChar125RouteImport } from './routes/_marketing/{-$pageId}'
import { Route as MarketingLoginRouteImport } from './routes/_marketing/login'
import { Route as Live_sitePageIdRouteImport } from './routes/_live_site/$pageId'
import { Route as AppTemplatesRouteRouteImport } from './routes/_app/templates/route'
import { Route as AppDeveloperRouteRouteImport } from './routes/_app/developer/route'
import { Route as AppDashboardRouteRouteImport } from './routes/_app/dashboard/route'
import { Route as AppCustomDomainRouteRouteImport } from './routes/_app/custom-domain/route'
import { Route as AppTemplatesIndexRouteImport } from './routes/_app/templates/index'
import { Route as AppSitePageIdRouteImport } from './routes/_app/site/$pageId'
import { Route as AppTemplatesInstallTemplateIdRouteImport } from './routes/_app/templates/install/$templateId'

const MarketingRouteRoute = MarketingRouteRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingChar123PageIdChar125Route =
  MarketingChar123PageIdChar125RouteImport.update({
    id: '/{-$pageId}',
    path: '/{-$pageId}',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingLoginRoute = MarketingLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const Live_sitePageIdRoute = Live_sitePageIdRouteImport.update({
  id: '/_live_site/$pageId',
  path: '/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRouteRoute = AppTemplatesRouteRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDeveloperRouteRoute = AppDeveloperRouteRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRouteRoute = AppDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomDomainRouteRoute = AppCustomDomainRouteRouteImport.update({
  id: '/custom-domain',
  path: '/custom-domain',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTemplatesRouteRoute,
} as any)
const AppSitePageIdRoute = AppSitePageIdRouteImport.update({
  id: '/site/$pageId',
  path: '/site/$pageId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTemplatesInstallTemplateIdRoute =
  AppTemplatesInstallTemplateIdRouteImport.update({
    id: '/install/$templateId',
    path: '/install/$templateId',
    getParentRoute: () => AppTemplatesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingRouteRouteWithChildren
  '/custom-domain': typeof AppCustomDomainRouteRoute
  '/dashboard': typeof AppDashboardRouteRoute
  '/developer': typeof AppDeveloperRouteRoute
  '/templates': typeof AppTemplatesRouteRouteWithChildren
  '/$pageId': typeof Live_sitePageIdRoute
  '/login': typeof MarketingLoginRoute
  '/{-$pageId}': typeof MarketingChar123PageIdChar125Route
  '/site/$pageId': typeof AppSitePageIdRoute
  '/templates/': typeof AppTemplatesIndexRoute
  '/templates/install/$templateId': typeof AppTemplatesInstallTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingRouteRouteWithChildren
  '/custom-domain': typeof AppCustomDomainRouteRoute
  '/dashboard': typeof AppDashboardRouteRoute
  '/developer': typeof AppDeveloperRouteRoute
  '/$pageId': typeof Live_sitePageIdRoute
  '/login': typeof MarketingLoginRoute
  '/{-$pageId}': typeof MarketingChar123PageIdChar125Route
  '/site/$pageId': typeof AppSitePageIdRoute
  '/templates': typeof AppTemplatesIndexRoute
  '/templates/install/$templateId': typeof AppTemplatesInstallTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_marketing': typeof MarketingRouteRouteWithChildren
  '/_app/custom-domain': typeof AppCustomDomainRouteRoute
  '/_app/dashboard': typeof AppDashboardRouteRoute
  '/_app/developer': typeof AppDeveloperRouteRoute
  '/_app/templates': typeof AppTemplatesRouteRouteWithChildren
  '/_live_site/$pageId': typeof Live_sitePageIdRoute
  '/_marketing/login': typeof MarketingLoginRoute
  '/_marketing/{-$pageId}': typeof MarketingChar123PageIdChar125Route
  '/_app/site/$pageId': typeof AppSitePageIdRoute
  '/_app/templates/': typeof AppTemplatesIndexRoute
  '/_app/templates/install/$templateId': typeof AppTemplatesInstallTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/custom-domain'
    | '/dashboard'
    | '/developer'
    | '/templates'
    | '/$pageId'
    | '/login'
    | '/{-$pageId}'
    | '/site/$pageId'
    | '/templates/'
    | '/templates/install/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/custom-domain'
    | '/dashboard'
    | '/developer'
    | '/$pageId'
    | '/login'
    | '/{-$pageId}'
    | '/site/$pageId'
    | '/templates'
    | '/templates/install/$templateId'
  id:
    | '__root__'
    | '/_app'
    | '/_marketing'
    | '/_app/custom-domain'
    | '/_app/dashboard'
    | '/_app/developer'
    | '/_app/templates'
    | '/_live_site/$pageId'
    | '/_marketing/login'
    | '/_marketing/{-$pageId}'
    | '/_app/site/$pageId'
    | '/_app/templates/'
    | '/_app/templates/install/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  MarketingRouteRoute: typeof MarketingRouteRouteWithChildren
  Live_sitePageIdRoute: typeof Live_sitePageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/{-$pageId}': {
      id: '/_marketing/{-$pageId}'
      path: '/{-$pageId}'
      fullPath: '/{-$pageId}'
      preLoaderRoute: typeof MarketingChar123PageIdChar125RouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/login': {
      id: '/_marketing/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MarketingLoginRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_live_site/$pageId': {
      id: '/_live_site/$pageId'
      path: '/$pageId'
      fullPath: '/$pageId'
      preLoaderRoute: typeof Live_sitePageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/developer': {
      id: '/_app/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AppDeveloperRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/custom-domain': {
      id: '/_app/custom-domain'
      path: '/custom-domain'
      fullPath: '/custom-domain'
      preLoaderRoute: typeof AppCustomDomainRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/templates/': {
      id: '/_app/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppTemplatesRouteRoute
    }
    '/_app/site/$pageId': {
      id: '/_app/site/$pageId'
      path: '/site/$pageId'
      fullPath: '/site/$pageId'
      preLoaderRoute: typeof AppSitePageIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/templates/install/$templateId': {
      id: '/_app/templates/install/$templateId'
      path: '/install/$templateId'
      fullPath: '/templates/install/$templateId'
      preLoaderRoute: typeof AppTemplatesInstallTemplateIdRouteImport
      parentRoute: typeof AppTemplatesRouteRoute
    }
  }
}

interface AppTemplatesRouteRouteChildren {
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
  AppTemplatesInstallTemplateIdRoute: typeof AppTemplatesInstallTemplateIdRoute
}

const AppTemplatesRouteRouteChildren: AppTemplatesRouteRouteChildren = {
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
  AppTemplatesInstallTemplateIdRoute: AppTemplatesInstallTemplateIdRoute,
}

const AppTemplatesRouteRouteWithChildren =
  AppTemplatesRouteRoute._addFileChildren(AppTemplatesRouteRouteChildren)

interface AppRouteRouteChildren {
  AppCustomDomainRouteRoute: typeof AppCustomDomainRouteRoute
  AppDashboardRouteRoute: typeof AppDashboardRouteRoute
  AppDeveloperRouteRoute: typeof AppDeveloperRouteRoute
  AppTemplatesRouteRoute: typeof AppTemplatesRouteRouteWithChildren
  AppSitePageIdRoute: typeof AppSitePageIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCustomDomainRouteRoute: AppCustomDomainRouteRoute,
  AppDashboardRouteRoute: AppDashboardRouteRoute,
  AppDeveloperRouteRoute: AppDeveloperRouteRoute,
  AppTemplatesRouteRoute: AppTemplatesRouteRouteWithChildren,
  AppSitePageIdRoute: AppSitePageIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface MarketingRouteRouteChildren {
  MarketingLoginRoute: typeof MarketingLoginRoute
  MarketingChar123PageIdChar125Route: typeof MarketingChar123PageIdChar125Route
}

const MarketingRouteRouteChildren: MarketingRouteRouteChildren = {
  MarketingLoginRoute: MarketingLoginRoute,
  MarketingChar123PageIdChar125Route: MarketingChar123PageIdChar125Route,
}

const MarketingRouteRouteWithChildren = MarketingRouteRoute._addFileChildren(
  MarketingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  MarketingRouteRoute: MarketingRouteRouteWithChildren,
  Live_sitePageIdRoute: Live_sitePageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
