import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { writeFile } from "node:fs/promises";

const MAPPING_FILE_NAME = "notion-orm.generated.ts";

/**
 * Get the absolute path to the mapping file
 * @param cwd - Current working directory (defaults to process.cwd())
 * @returns Absolute path to notion-orm.generated.ts
 */
export function getMappingFilePath(cwd: string = process.cwd()): string {
  return resolve(cwd, MAPPING_FILE_NAME);
}

/**
 * Check if the mapping file exists
 * @param cwd - Current working directory
 * @returns True if notion-orm.generated.ts exists
 */
export function mappingFileExists(cwd: string = process.cwd()): boolean {
  return existsSync(getMappingFilePath(cwd));
}

/**
 * Load the existing mapping from notion-orm.generated.ts
 * Uses dynamic import via file URL for ESM compatibility
 * @param cwd - Current working directory
 * @returns Record mapping table titles to database IDs
 */
export async function loadMapping(cwd: string = process.cwd()): Promise<Record<string, string>> {
  const filePath = getMappingFilePath(cwd);

  if (!existsSync(filePath)) {
    return {};
  }

  try {
    const fileUrl = pathToFileURL(filePath).href;
    const module = await import(fileUrl);
    return (module.databaseMapping as Record<string, string>) || {};
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.warn(
      `Warning: Failed to load mapping file at ${filePath}: ${message}. Starting with empty mapping.`,
    );
    return {};
  }
}

/**
 * Write the mapping to notion-orm.generated.ts
 * Generates a TypeScript file with proper types
 * @param mapping - Record mapping table titles to database IDs
 * @param cwd - Current working directory
 */
export async function writeMapping(
  mapping: Record<string, string>,
  cwd: string = process.cwd(),
): Promise<void> {
  const filePath = getMappingFilePath(cwd);

  const entries = Object.entries(mapping);
  const lines: string[] = [
    `// Auto-generated by notion-orm push`,
    `// Do not edit manually`,
    ``,
    `export const databaseMapping = {`,
  ];

  for (const [key, value] of entries) {
    lines.push(`  "${key}": "${value}",`);
  }

  lines.push(`} as const;`);
  lines.push(``);
  lines.push(`export type DatabaseMapping = typeof databaseMapping;`);
  lines.push(``);

  await writeFile(filePath, lines.join("\n"), "utf-8");
}
