import type { NotionTable } from "./table.js";
import { InferInsertType, NotionPagePropertyRequest } from "./types.js";
import { convertToPageProperties } from "./page-properties.js";
import { createNotionApi, NotionApi } from "@nastro/notion-api";
import path from "node:path";
import { BlockObjectRequest } from "@notionhq/client";

// =============================================================================
// Mapping Resolution
// =============================================================================
// The mapping file (notion-orm.generated.ts) is generated by the CLI push
// command and lives in the project root. We attempt to import it dynamically.
// =============================================================================

let _cachedMapping: Record<string, string> | null = null;

function resolveConfig(): Record<string, string> {
  if (_cachedMapping) return _cachedMapping;

  const filePath = path.join(process.cwd(), "notion-orm.generated.ts");
  // @ts-expect-error Mapping file is generated at runtime by the CLI
  const { databaseMapping } = import(filePath);
  _cachedMapping = setMapping(databaseMapping);

  return _cachedMapping;
}

export function setMapping(mapping: Record<string, string>): Record<string, string> {
  _cachedMapping = mapping;
  return _cachedMapping;
}

// =============================================================================
// Insert Builder
// =============================================================================

/**
 * Insert builder for a specific NotionTable.
 *
 * Provides a chainable `.values()` method that accepts typed insert data,
 * converts it to Notion page properties, and creates the page via the API.
 *
 * @example
 * ```ts
 * const db = new DB({ token: "...", rootPageId: "..." });
 * await db.insert(tasksTable).values({
 *   title: "My new task",
 *   status: "Todo",
 *   priority: "High",
 * });
 * ```
 */
export class Insert<T extends NotionTable, M, S> {
  constructor(
    private table: T,
    private token: string,
    private config?: Record<string, string>,
  ) {}

  values(data: InferInsertType<T, M, S>) {
    const mapping = this.config ?? resolveConfig();
    const databaseId = mapping[this.table.title];

    if (!databaseId) {
      throw new Error(
        `Database ID not found for table "${this.table.title}". ` +
          `Run 'nastro-orm push' first to generate the mapping file.`,
      );
    }

    return {
      execute: async () => {
        const notion = createNotionApi({ token: this.token });
        const props = convertToPageProperties(data, this.table);
        return handleCreatePage({ dbId: databaseId, props, notion });
      },
    };
  }
}

function handleCreatePage({
  dbId,
  props,
  notion,
  content,
}: {
  dbId: string;
  props: NotionPagePropertyRequest;
  notion: NotionApi;
  content?: BlockObjectRequest[];
}) {
  return notion.createPage({
    parent: { type: "database_id", database_id: dbId },
    properties: props,
    content,
  });
}
