import type { PageObjectResponse } from "@notionhq/client";
import { Client } from "@notionhq/client";
import type { NotionTable, InferInsertType } from "./table.js";
import { convertToPageProperties } from "./page-properties.js";

// =============================================================================
// Mapping Resolution
// =============================================================================
// The mapping file (notion-orm.generated.ts) is generated by the CLI push
// command and lives in the project root. We attempt to import it dynamically.
// =============================================================================

let _cachedMapping: Record<string, string> | null = null;

async function resolveMapping(): Promise<Record<string, string>> {
  if (_cachedMapping) return _cachedMapping;

  try {
    // @ts-expect-error Mapping file is generated at runtime by the CLI
    const { databaseMapping } = await import("../../../notion-orm.generated.ts");
    _cachedMapping = (databaseMapping as Record<string, string>) || {};
  } catch {
    _cachedMapping = {};
  }

  return _cachedMapping;
}

export function setMapping(mapping: Record<string, string>): void {
  _cachedMapping = mapping;
}

// =============================================================================
// Insert Builder
// =============================================================================

/**
 * Insert builder for a specific NotionTable.
 *
 * Provides a chainable `.values()` method that accepts typed insert data,
 * converts it to Notion page properties, and creates the page via the API.
 *
 * @example
 * ```ts
 * const db = new DB({ token: "...", rootPageId: "..." });
 * await db.insert(tasksTable).values({
 *   title: "My new task",
 *   status: "Todo",
 *   priority: "High",
 * });
 * ```
 */
export class Insert<T extends NotionTable> {
  private table: T;
  private token: string;
  private mappingOverride?: Record<string, string>;

  constructor(table: T, token: string, mappingOverride?: Record<string, string>) {
    this.table = table;
    this.token = token;
    this.mappingOverride = mappingOverride;
  }

  /**
   * Insert a new row into the Notion database.
   *
   * @param data - Typed insert values matching the table schema
   * @returns The created Notion page object
   * @throws Error if the table is not found in the mapping, or if the API call fails
   */
  async values(data: InferInsertType<T>): Promise<PageObjectResponse> {
    const mapping = this.mappingOverride ?? (await resolveMapping());
    const databaseId = mapping[this.table.title];

    if (!databaseId) {
      throw new Error(
        `Database ID not found for table "${this.table.title}". ` +
          `Run 'nastro-orm push' first to generate the mapping file.`,
      );
    }

    const notion = new Client({ auth: this.token });

    const properties = convertToPageProperties(
      this.table as unknown as { properties: T["properties"] },
      data as Record<string, unknown>,
    );

    const response = await notion.pages.create({
      parent: {
        database_id: databaseId,
      },
      properties,
    });

    return response as PageObjectResponse;
  }
}
