import type { Column } from "./types.ts";

/**
 * Table definition structure
 * Represents a complete Notion database schema
 */
export interface NotionTable<TProperties extends Record<string, Column> = Record<string, Column>> {
  _type: "table";
  title: string;
  properties: TProperties;
}

/**
 * Table builder function
 * Creates a table definition that can be used for:
 * 1. Type inference via InferType<typeof table>
 * 2. CLI push to create/update databases
 * 3. Query building with .from(table)
 *
 * @example
 * ```typescript
 * const projectsTable = table({
 *   title: "Projects",
 *   properties: {
 *     name: title({ name: "Project Name" }),
 *     status: status({ name: "Status" }),
 *   }
 * });
 *
 * type Project = InferType<typeof projectsTable>;
 * // { id: string, name: string, status: string, ... }
 * ```
 */
export function table<T extends Record<string, Column>>(
  title: string,
  properties: T,
): NotionTable<T> {
  const props = Object.entries(properties);
  const record: Record<string, Column> = {};

  for (const prop of props) {
    const [name, column] = prop;
    const columnWithName = column;

    if (!column.name) {
      columnWithName.name = name;
    }
    record[name] = columnWithName;
  }

  return {
    _type: "table",
    title: title,
    properties: record as T,
  };
}

/**
 * Infer the TypeScript type from a table definition
 * This extracts the user-facing types for each column
 *
 * @example
 * ```typescript
 * const projectsTable = table({...});
 * type Project = InferType<typeof projectsTable>;
 * ```
 */
export type InferType<T extends NotionTable> = {
  // Always include the page ID
  id: string;
} & {
  // Map each property to its TypeScript type
  [K in keyof T["properties"]]: InferColumnType<T["properties"][K]>;
};

/**
 * Infer the TypeScript type for insert operations from a table definition
 * - Excludes id (auto-generated by Notion)
 * - Excludes read-only columns: formula, rollup, unique_id, created_time, created_by, last_edited_time, last_edited_by
 * - Makes title required (must have at least a title when creating)
 * - Makes all other writable columns optional
 *
 * @example
 * ```typescript
 * const projectsTable = table({...});
 * type ProjectInsert = InferInsertType<typeof projectsTable>;
 * // { name: string, status?: string, ... }
 * ```
 */
export type InferInsertType<T extends NotionTable> = {
  // Always require title for inserts
  [K in keyof T["properties"] as T["properties"][K] extends { type: "title" }
    ? K
    : never]-?: InferColumnInsertType<T["properties"][K]>;
} & {
  // Make all other writable columns optional, filter out read-only types (never)
  [K in keyof T["properties"] as T["properties"][K] extends { type: "title" }
    ? never
    : InferColumnInsertType<T["properties"][K]> extends never
      ? never
      : K]?: InferColumnInsertType<T["properties"][K]>;
};

/**
 * Infer the TypeScript insert type for a single column
 * Maps Notion column types to TypeScript types for insertion
 * Returns never for read-only columns
 */
type InferColumnInsertType<TColumn extends Column> = TColumn extends {
  type: "title";
}
  ? string // Title is always required string for insert
  : TColumn extends { type: "rich_text" }
    ? string // Rich text as plain string
    : TColumn extends { type: "number" }
      ? number
      : TColumn extends { type: "select" }
        ? string // Select option name
        : TColumn extends { type: "multi_select" }
          ? string[] // Array of option names
          : TColumn extends { type: "status" }
            ? string // Status option name
            : TColumn extends { type: "date" }
              ? string
              : TColumn extends { type: "people" }
                ? Array<{ id: string }> // User IDs for insert
                : TColumn extends { type: "files" }
                  ? Array<{
                      name: string;
                      url: string;
                      type: "external" | "file";
                    }>
                  : TColumn extends { type: "checkbox" }
                    ? boolean
                    : TColumn extends { type: "url" }
                      ? string
                      : TColumn extends { type: "email" }
                        ? string
                        : TColumn extends { type: "phone_number" }
                          ? string
                          : TColumn extends { type: "relation" }
                            ? string[] // Array of related page IDs
                            : // Read-only columns - filtered out
                              TColumn extends { type: "formula" }
                              ? never
                              : TColumn extends { type: "rollup" }
                                ? never
                                : TColumn extends { type: "unique_id" }
                                  ? never
                                  : TColumn extends { type: "created_time" }
                                    ? never
                                    : TColumn extends { type: "created_by" }
                                      ? never
                                      : TColumn extends {
                                            type: "last_edited_time";
                                          }
                                        ? never
                                        : TColumn extends {
                                              type: "last_edited_by";
                                            }
                                          ? never
                                          : never;

/**
 * Infer the TypeScript type for a single column
 * Maps Notion column types to TypeScript types
 */
type InferColumnType<TColumn extends Column> = TColumn extends { type: "title" }
  ? string // Title is always string (concatenated rich text)
  : TColumn extends { type: "rich_text" }
    ? string // Rich text as plain string
    : TColumn extends { type: "number" }
      ? number | null
      : TColumn extends { type: "select" }
        ? string | null // Select option name
        : TColumn extends { type: "multi_select" }
          ? string[] // Array of option names
          : TColumn extends { type: "status" }
            ? string | null // Status option name
            : TColumn extends { type: "date" }
              ? string | null
              : TColumn extends { type: "people" }
                ? Array<{ id: string; name?: string; email?: string }> // User objects
                : TColumn extends { type: "files" }
                  ? Array<{
                      name: string;
                      url: string;
                      type: "external" | "file";
                    }>
                  : TColumn extends { type: "checkbox" }
                    ? boolean
                    : TColumn extends { type: "url" }
                      ? string | null
                      : TColumn extends { type: "email" }
                        ? string | null
                        : TColumn extends { type: "phone_number" }
                          ? string | null
                          : TColumn extends { type: "relation" }
                            ? string[] // Array of related page IDs
                            : TColumn extends { type: "formula" }
                              ? string | number | boolean | { start: string; end?: string } | null // Depends on formula result type
                              : TColumn extends { type: "rollup" }
                                ? unknown // Rollup type depends on function and property
                                : TColumn extends { type: "unique_id" }
                                  ? string // Formatted as "PREFIX-123"
                                  : TColumn extends { type: "created_time" }
                                    ? string // ISO 8601 date string
                                    : TColumn extends { type: "created_by" }
                                      ? {
                                          id: string;
                                          name?: string;
                                          email?: string;
                                        }
                                      : TColumn extends {
                                            type: "last_edited_time";
                                          }
                                        ? string // ISO 8601 date string
                                        : TColumn extends {
                                              type: "last_edited_by";
                                            }
                                          ? {
                                              id: string;
                                              name?: string;
                                              email?: string;
                                            }
                                          : never;
