// Column type definitions matching Notion API PropertyConfigurationRequest
// Reference: https://developers.notion.com/reference/property-object

// ============== Base Types ==============

export type NotionColor =
  | "default"
  | "gray"
  | "brown"
  | "orange"
  | "yellow"
  | "green"
  | "blue"
  | "purple"
  | "pink"
  | "red";

export type NumberFormat =
  | "number"
  | "number_with_commas"
  | "percent"
  | "dollar"
  | "canadian_dollar"
  | "euro"
  | "pound"
  | "yen"
  | "ruble"
  | "rupee"
  | "won"
  | "yuan"
  | "real"
  | "lira"
  | "rupiah"
  | "franc"
  | "hong_kong_dollar"
  | "new_zealand_dollar"
  | "krona"
  | "norwegian_krone"
  | "mexican_peso"
  | "rand"
  | "new_taiwan_dollar"
  | "danish_krone"
  | "zloty"
  | "baht"
  | "forint"
  | "koruna"
  | "shekel"
  | "chilean_peso"
  | "philippine_peso"
  | "dirham"
  | "colombian_peso"
  | "riyal"
  | "ringgit"
  | "leu"
  | "argentine_peso"
  | "uruguayan_peso"
  | "singapore_dollar";

export type RollupFunction =
  | "count"
  | "count_values"
  | "empty"
  | "not_empty"
  | "unique"
  | "show_unique"
  | "percent_empty"
  | "percent_not_empty"
  | "sum"
  | "average"
  | "median"
  | "min"
  | "max"
  | "range"
  | "earliest_date"
  | "latest_date"
  | "date_range"
  | "checked"
  | "unchecked"
  | "percent_checked"
  | "percent_unchecked"
  | "count_per_group"
  | "percent_per_group"
  | "show_original";

// ============== Option Types ==============

export interface SelectOption {
  name: string;
  color?: NotionColor;
  description?: string | null;
}

export interface StatusOption {
  name: string;
  color?: NotionColor;
  id?: string; // auto-generated by Notion
}

// ============== Column Base Interface ==============

export interface ColumnBase {
  name?: string;
  description?: string;
}

// ============== Writable Columns ==============

// Title (required, exactly one per table)
export interface TitleColumn extends ColumnBase {
  type: "title";
  title: {};
}

// Rich Text
export interface RichTextColumn extends ColumnBase {
  type: "rich_text";
  rich_text: {};
}

// Number
export interface NumberColumn extends ColumnBase {
  type: "number";
  number: {
    format?: NumberFormat;
  };
}

// Select
export interface SelectColumn extends ColumnBase {
  type: "select";
  select: {
    options: SelectOption[];
  };
}

// Multi Select
export interface MultiSelectColumn extends ColumnBase {
  type: "multi_select";
  multi_select: {
    options?: SelectOption[];
  };
}

// Status
export interface StatusColumn extends ColumnBase {
  type: "status";
  status: {
    options: StatusOption[];
  };
}

// Date
export interface DateColumn extends ColumnBase {
  type: "date";
  date: {};
}

// People
export interface PeopleColumn extends ColumnBase {
  type: "people";
  people: {};
}

// Files
export interface FilesColumn extends ColumnBase {
  type: "files";
  files: {};
}

// Checkbox
export interface CheckboxColumn extends ColumnBase {
  type: "checkbox";
  checkbox: {};
}

// URL
export interface UrlColumn extends ColumnBase {
  type: "url";
  url: {};
}

// Email
export interface EmailColumn extends ColumnBase {
  type: "email";
  email: {};
}

// Phone Number
export interface PhoneNumberColumn extends ColumnBase {
  type: "phone_number";
  phone_number: {};
}

// Relation (links to another table)
export interface RelationColumn extends ColumnBase {
  type: "relation";
  relation: {
    // data_source_id is resolved during push
    data_source_id?: string;
  };
  // Reference to another table's export name (for deferred resolution)
  relatedTo?: string;
}

// ============== Computed/Read-only Columns ==============

// Formula (computed, read-only)
export interface FormulaColumn extends ColumnBase {
  type: "formula";
  formula: {
    expression: string;
  };
}

// Rollup (computed, read-only)
export interface RollupColumn extends ColumnBase {
  type: "rollup";
  rollup: {
    function: RollupFunction;
    relation_property_name: string;
    rollup_property_name: string;
  };
}

// Unique ID (auto-generated, read-only)
export interface UniqueIdColumn extends ColumnBase {
  type: "unique_id";
  unique_id: {
    prefix?: string | null;
  };
}

// ============== System Columns (read-only) ==============

export interface CreatedTimeColumn extends ColumnBase {
  type: "created_time";
  created_time: {};
}

export interface CreatedByColumn extends ColumnBase {
  type: "created_by";
  created_by: {};
}

export interface LastEditedTimeColumn extends ColumnBase {
  type: "last_edited_time";
  last_edited_time: {};
}

export interface LastEditedByColumn extends ColumnBase {
  type: "last_edited_by";
  last_edited_by: {};
}

// ============== Union Type ==============

export type Column =
  | TitleColumn
  | RichTextColumn
  | NumberColumn
  | SelectColumn
  | MultiSelectColumn
  | StatusColumn
  | DateColumn
  | PeopleColumn
  | FilesColumn
  | CheckboxColumn
  | UrlColumn
  | EmailColumn
  | PhoneNumberColumn
  | RelationColumn
  | FormulaColumn
  | RollupColumn
  | UniqueIdColumn
  | CreatedTimeColumn
  | CreatedByColumn
  | LastEditedTimeColumn
  | LastEditedByColumn;
