// Column type definitions matching Notion API PropertyConfigurationRequest
// Reference: https://developers.notion.com/reference/property-object

// ============== Base Types ==============

export type NotionColor =
  | "default"
  | "gray"
  | "brown"
  | "orange"
  | "yellow"
  | "green"
  | "blue"
  | "purple"
  | "pink"
  | "red";

export type NumberFormat =
  | "number"
  | "number_with_commas"
  | "percent"
  | "dollar"
  | "canadian_dollar"
  | "euro"
  | "pound"
  | "yen"
  | "ruble"
  | "rupee"
  | "won"
  | "yuan"
  | "real"
  | "lira"
  | "rupiah"
  | "franc"
  | "hong_kong_dollar"
  | "new_zealand_dollar"
  | "krona"
  | "norwegian_krone"
  | "mexican_peso"
  | "rand"
  | "new_taiwan_dollar"
  | "danish_krone"
  | "zloty"
  | "baht"
  | "forint"
  | "koruna"
  | "shekel"
  | "chilean_peso"
  | "philippine_peso"
  | "dirham"
  | "colombian_peso"
  | "riyal"
  | "ringgit"
  | "leu"
  | "argentine_peso"
  | "uruguayan_peso"
  | "singapore_dollar";

export type RollupFunction =
  | "count"
  | "count_values"
  | "empty"
  | "not_empty"
  | "unique"
  | "show_unique"
  | "percent_empty"
  | "percent_not_empty"
  | "sum"
  | "average"
  | "median"
  | "min"
  | "max"
  | "range"
  | "earliest_date"
  | "latest_date"
  | "date_range"
  | "checked"
  | "unchecked"
  | "percent_checked"
  | "percent_unchecked"
  | "count_per_group"
  | "percent_per_group"
  | "show_original";

// ============== Option Types ==============

export interface SelectOption {
  name: string;
  color?: NotionColor;
  description?: string | null;
}

export interface StatusOption {
  name: string;
  color?: NotionColor;
  id?: string; // auto-generated by Notion
}

// ============== Column Base Interface ==============

export interface ColumnBase {
  id?: string;
  name?: string;
  description?: string;
}

// ============== Writable Columns ==============

// Title (required, exactly one per table)
export interface TitleColumn extends ColumnBase {
  type: "title";
  title: {};
}

// Rich Text
export interface RichTextColumn extends ColumnBase {
  type: "rich_text";
  rich_text: {};
}

// Number
export interface NumberColumn extends ColumnBase {
  type: "number";
  number: {
    format?: NumberFormat;
  };
}

// Select
export interface SelectColumn extends ColumnBase {
  type: "select";
  select: {
    options: SelectOption[];
  };
}

// Multi Select
export interface MultiSelectColumn extends ColumnBase {
  type: "multi_select";
  multi_select: {
    options?: SelectOption[];
  };
}

// Status
export interface StatusColumn extends ColumnBase {
  type: "status";
  status: {
    options: StatusOption[];
  };
}

// Date
export interface DateColumn extends ColumnBase {
  type: "date";
  date: {};
}

// People
export interface PeopleColumn extends ColumnBase {
  type: "people";
  people: {};
}

// Files
export interface FilesColumn extends ColumnBase {
  type: "files";
  files: {};
}

// Checkbox
export interface CheckboxColumn extends ColumnBase {
  type: "checkbox";
  checkbox: {};
}

// URL
export interface UrlColumn extends ColumnBase {
  type: "url";
  url: {};
}

// Email
export interface EmailColumn extends ColumnBase {
  type: "email";
  email: {};
}

// Phone Number
export interface PhoneNumberColumn extends ColumnBase {
  type: "phone_number";
  phone_number: {};
}

// Relation (links to another table)
export interface RelationColumn extends ColumnBase {
  type: "relation";
  relation: {
    // data_source_id is resolved during push
    data_source_id?: string;
  };
  // Reference to another table's export name (for deferred resolution)
  relatedTo?: string;
}

// ============== Computed/Read-only Columns ==============

// Formula (computed, read-only)
export interface FormulaColumn extends ColumnBase {
  type: "formula";
  formula: {
    expression: string;
  };
}

// Rollup (computed, read-only)
export interface RollupColumn extends ColumnBase {
  type: "rollup";
  rollup: {
    function: RollupFunction;
    relation_property_name: string;
    rollup_property_name: string;
  };
}

// Unique ID (auto-generated, read-only)
export interface UniqueIdColumn extends ColumnBase {
  type: "unique_id";
  unique_id: {
    prefix?: string | null;
  };
}

// ============== System Columns (read-only) ==============

export interface CreatedTimeColumn extends ColumnBase {
  type: "created_time";
  created_time: {};
}

export interface CreatedByColumn extends ColumnBase {
  type: "created_by";
  created_by: {};
}

export interface LastEditedTimeColumn extends ColumnBase {
  type: "last_edited_time";
  last_edited_time: {};
}

export interface LastEditedByColumn extends ColumnBase {
  type: "last_edited_by";
  last_edited_by: {};
}

export interface LastVisitedTimeColumn extends ColumnBase {
  type: "last_visited_time";
  last_visited_time: {};
}

export interface PlaceColumn extends ColumnBase {
  type: "place";
  place: {};
}

export interface ButtonColumn extends ColumnBase {
  type: "button";
  button: {};
}

export interface LocationColumn extends ColumnBase {
  type: "location";
  location: {};
}

export interface VerificationColumn extends ColumnBase {
  type: "verification";
  verification: {};
}

// ============== Union Type ==============

export type Column =
  | TitleColumn
  | RichTextColumn
  | NumberColumn
  | SelectColumn
  | MultiSelectColumn
  | StatusColumn
  | DateColumn
  | PeopleColumn
  | FilesColumn
  | CheckboxColumn
  | UrlColumn
  | EmailColumn
  | PhoneNumberColumn
  | RelationColumn
  | FormulaColumn
  | RollupColumn
  | UniqueIdColumn
  | CreatedTimeColumn
  | CreatedByColumn
  | LastEditedTimeColumn
  | LastEditedByColumn
  | LastVisitedTimeColumn
  | PlaceColumn
  | ButtonColumn
  | LocationColumn
  | VerificationColumn;

/**
 * Table definition structure
 * Represents a complete Notion database schema
 */
export interface NotionTable<TProperties extends Record<string, Column> = Record<string, Column>> {
  _type: "table";
  title: string;
  properties: TProperties;
}

/**
 * Infer the TypeScript type for insert operations from a table definition
 * - Excludes id (auto-generated by Notion)
 * - Excludes read-only columns: formula, rollup, unique_id, created_time, created_by, last_edited_time, last_edited_by
 * - Makes title required (must have at least a title when creating)
 * - Makes all other writable columns optional
 *
 * @example
 * ```typescript
 * const projectsTable = table({...});
 * type ProjectInsert = InferInsertType<typeof projectsTable>;
 * // { name: string, status?: string, ... }
 * ```
 */
export type InferInsertType<T extends NotionTable, MultiSelectEnum, SelectEnum, StatusEnum> = {
  // Always require title for inserts
  [K in keyof T["properties"] as T["properties"][K] extends { type: "title" }
    ? K
    : never]-?: InferColumnInsertType<T["properties"][K], MultiSelectEnum, SelectEnum, StatusEnum>;
} & {
  // Make all other writable columns optional, filter out read-only types (never)
  [K in keyof T["properties"] as T["properties"][K] extends { type: "title" }
    ? never
    : InferColumnInsertType<
          T["properties"][K],
          MultiSelectEnum,
          SelectEnum,
          StatusEnum
        > extends never
      ? never
      : K]?: InferColumnInsertType<T["properties"][K], MultiSelectEnum, SelectEnum, StatusEnum>;
};

export type ColumnTypeMap<MultiSelectEnum, SelectEnum, StatusEnum> = {
  title: string;
  rich_text: string;
  number: number;
  select: SelectEnum;
  multi_select: Array<{ name: MultiSelectEnum }>;
  status: StatusEnum;
  date: string;
  people: Array<{ id: string }>;
  files: Array<{
    name: string;
    url: string;
    type: "external" | "file";
  }>;
  checkbox: boolean;
  url: string;
  email: string;
  phone_number: string;
};

/**
 * Infer the TypeScript insert type for a single column
 * Maps Notion column types to TypeScript types for insertion
 */
export type InferColumnInsertType<
  TColumn extends Column,
  MultiSelect,
  Select,
  StatusEnum,
> = TColumn["type"] extends keyof ColumnTypeMap<MultiSelect, Select, StatusEnum>
  ? ColumnTypeMap<MultiSelect, Select, StatusEnum>[TColumn["type"]]
  : never;

// ============== Select Types ==============

/**
 * Column type map for query/select result types.
 * Includes read-only columns and handles nullability for optional fields.
 * Excludes formula and rollup (not selectable).
 */
export type ColumnSelectTypeMap<MultiSelect, Select> = {
  title: string;
  rich_text: string;
  number: number | null;
  select: Select;
  multi_select: Array<{ name: MultiSelect }>;
  status: string;
  date: string | null;
  people: Array<{ id: string }>;
  files: Array<{ name: string; url: string; type: "external" | "file" }>;
  checkbox: boolean;
  url: string | null;
  email: string | null;
  phone_number: string | null;
  relation: Array<{ id: string }>;
  unique_id: string;
  created_time: string;
  created_by: string;
  last_edited_time: string;
  last_edited_by: string;
};

/**
 * Infer the TypeScript select type for a single column.
 * Maps Notion column types to TypeScript types for query results.
 * Excludes formula and rollup (they return never and are filtered out).
 */
export type InferColumnSelectType<
  TColumn extends Column,
  MultiSelect,
  Select,
> = TColumn["type"] extends keyof ColumnSelectTypeMap<MultiSelect, Select>
  ? ColumnSelectTypeMap<MultiSelect, Select>[TColumn["type"]]
  : never;

/**
 * Infer the TypeScript type for select/query operations from a table definition.
 * - Always includes `id: string` (page ID)
 * - Includes all columns except formula and rollup (read-only columns are present)
 * - Nullable types for optional fields (number, date, url, email, phone_number)
 *
 * @example
 * ```typescript
 * const projectsTable = table({...});
 * type Project = InferSelectType<typeof projectsTable, string, string>;
 * // { id: string, name: string, status: string, budget: number | null, ... }
 * ```
 */
export type InferSelectType<T extends NotionTable, MultiSelectEnum, SelectEnum> = {
  id: string;
} & {
  [K in keyof T["properties"] as T["properties"][K] extends { type: "formula" } | { type: "rollup" }
    ? never
    : K]: InferColumnSelectType<T["properties"][K], MultiSelectEnum, SelectEnum>;
};

export type CheckboxPropertyRequest = {
  type?: "checkbox";
  checkbox: boolean;
};

export type DatePropertyRequest = {
  type?: "date";
  date: {
    start: string;
  };
};

export type EmailPropertyRequest = {
  type?: "email";
  email: string;
};

export type FilesPropertyRequest = {
  type?: "files";
  files: Array<{
    name: string;
    external: {
      url: string;
    };
  }>;
};

export type MultiSelectPropertyRequest = {
  type?: "multi_select";
  multi_select: Array<{
    name: string;
  }>;
};

export type NumberPropertyRequest = {
  type?: "number";
  number: number;
};

export type PeoplePropertyRequest = {
  type?: "people";
  people: Array<{
    object: "user";
    id: string;
  }>;
};

export type PhoneNumberPropertyRequest = {
  type?: "phone_number";
  phone_number: string;
};

export type RichTextPropertyRequest = {
  type?: "rich_text";
  rich_text: Array<{
    type: "text";
    text: {
      content: string;
      link?: { url: string };
    };
    annotations?: {
      bold: boolean;
      italic: boolean;
      strikethrough: boolean;
      underline: boolean;
      code: boolean;
      color: NotionColor;
    };
  }>;
};

export type SelectPropertyRequest = {
  type?: "select";
  select: {
    name: string;
  };
};

export type StatusPropertyRequest = {
  type?: "status";
  status: {
    name: string;
  };
};

export type TitlePropertyRequest = {
  type?: "title";
  title: Array<{
    type: "text";
    text: {
      content: string;
      link?: { url: string };
    };
    annotations?: {
      bold: boolean;
      italic: boolean;
      strikethrough: boolean;
      underline: boolean;
      code: boolean;
      color: NotionColor;
    };
  }>;
};

export type UrlPropertyRequest = {
  type?: "url";
  url: string;
};

export type NotionPagePropertyRequest = Record<
  string,
  | CheckboxPropertyRequest
  | DatePropertyRequest
  | EmailPropertyRequest
  | FilesPropertyRequest
  | MultiSelectPropertyRequest
  | NumberPropertyRequest
  | PeoplePropertyRequest
  | PhoneNumberPropertyRequest
  | RichTextPropertyRequest
  | SelectPropertyRequest
  | StatusPropertyRequest
  | TitlePropertyRequest
  | UrlPropertyRequest
>;

export type NotionPageProperties =
  | CheckboxPropertyRequest
  | DatePropertyRequest
  | EmailPropertyRequest
  | FilesPropertyRequest
  | MultiSelectPropertyRequest
  | NumberPropertyRequest
  | PeoplePropertyRequest
  | PhoneNumberPropertyRequest
  | RichTextPropertyRequest
  | SelectPropertyRequest
  | StatusPropertyRequest
  | TitlePropertyRequest
  | UrlPropertyRequest;
