// Auto-generated by notion-orm push
// Do not edit manually

export const databaseMapping = {
  "Tasks": "eb1ceeac-10ce-4b61-970b-ea1f5e312b80",
  "Projects": "8bd01f11-5c14-400f-a22a-57699d755654",
} as const;

export type DatabaseMapping = typeof databaseMapping;
